use portable_pty::{native_pty_system, CommandBuilder, MasterPty, PtySize};
use serde::Serialize;
use std::{
    collections::HashMap,
    env, fs,
    io::{Read, Write},
    path::{Path, PathBuf},
    process::Command,
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc, Mutex,
    },
    thread,
};
use tauri::{Emitter, Manager, WebviewUrl, WebviewWindow, WebviewWindowBuilder};

const MAX_SCROLLBACK_BYTES: usize = 2 * 1024 * 1024;
const LIBRARY_FILE_NAME: &str = "RiftDrift Library.riftdrift";
const ZSH_HIGHLIGHT_SCRIPT: &str = include_str!("../shell/riftdrift-highlighting.zsh");
const ZSHENV_WRAPPER: &str = r#"# Generated by RiftDrift. The user's own dotfiles remain authoritative.
export RIFTDRIFT_WRAPPER_ZDOTDIR="$ZDOTDIR"
export ZDOTDIR="$RIFTDRIFT_USER_ZDOTDIR"
if [[ -r "$ZDOTDIR/.zshenv" ]]; then
  source "$ZDOTDIR/.zshenv"
fi
export RIFTDRIFT_EFFECTIVE_ZDOTDIR="${ZDOTDIR:-$RIFTDRIFT_USER_ZDOTDIR}"
export ZDOTDIR="$RIFTDRIFT_WRAPPER_ZDOTDIR"
"#;
const ZPROFILE_WRAPPER: &str = r#"export ZDOTDIR="$RIFTDRIFT_EFFECTIVE_ZDOTDIR"
if [[ -r "$ZDOTDIR/.zprofile" ]]; then
  source "$ZDOTDIR/.zprofile"
fi
export RIFTDRIFT_EFFECTIVE_ZDOTDIR="${ZDOTDIR:-$RIFTDRIFT_EFFECTIVE_ZDOTDIR}"
export ZDOTDIR="$RIFTDRIFT_WRAPPER_ZDOTDIR"
"#;
const ZSHRC_WRAPPER: &str = r#"export ZDOTDIR="$RIFTDRIFT_EFFECTIVE_ZDOTDIR"
if [[ -r "$ZDOTDIR/.zshrc" ]]; then
  source "$ZDOTDIR/.zshrc"
fi
export RIFTDRIFT_EFFECTIVE_ZDOTDIR="${ZDOTDIR:-$RIFTDRIFT_EFFECTIVE_ZDOTDIR}"
export ZDOTDIR="$RIFTDRIFT_WRAPPER_ZDOTDIR"
if [[ -r "$RIFTDRIFT_ZSH_HIGHLIGHTER" ]]; then
  source "$RIFTDRIFT_ZSH_HIGHLIGHTER"
fi
export ZDOTDIR="$RIFTDRIFT_EFFECTIVE_ZDOTDIR"
unset RIFTDRIFT_WRAPPER_ZDOTDIR RIFTDRIFT_EFFECTIVE_ZDOTDIR RIFTDRIFT_USER_ZDOTDIR RIFTDRIFT_ZSH_HIGHLIGHTER
"#;

struct TerminalSession {
    master: Box<dyn MasterPty + Send>,
    writer: Box<dyn Write + Send>,
    child: Box<dyn portable_pty::Child + Send + Sync>,
    scrollback: Arc<Mutex<Vec<u8>>>,
}

struct TerminalState {
    next_id: AtomicU64,
    sessions: Mutex<HashMap<u64, TerminalSession>>,
}

#[derive(Default)]
struct PortableLibraryState {
    opened_path: Mutex<Option<String>>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct LibraryFile {
    path: String,
    contents: Option<String>,
}

impl Default for TerminalState {
    fn default() -> Self {
        Self {
            next_id: AtomicU64::new(1),
            sessions: Mutex::new(HashMap::new()),
        }
    }
}

fn default_library_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|directory| directory.join(LIBRARY_FILE_NAME))
        .map_err(|error| format!("Could not resolve the RiftDrift data directory: {error}"))
}

fn prepare_zsh_integration(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let directory = app
        .path()
        .app_cache_dir()
        .map_err(|error| format!("Could not resolve the shell integration directory: {error}"))?
        .join("shell-integration");
    write_zsh_integration(&directory)?;
    Ok(directory)
}

fn write_zsh_integration(directory: &Path) -> Result<(), String> {
    fs::create_dir_all(&directory)
        .map_err(|error| format!("Could not create {}: {error}", directory.display()))?;

    for (name, contents) in [
        (".zshenv", ZSHENV_WRAPPER),
        (".zprofile", ZPROFILE_WRAPPER),
        (".zshrc", ZSHRC_WRAPPER),
        ("riftdrift-highlighting.zsh", ZSH_HIGHLIGHT_SCRIPT),
    ] {
        let path = directory.join(name);
        fs::write(&path, contents)
            .map_err(|error| format!("Could not write {}: {error}", path.display()))?;
    }

    Ok(())
}

fn resolve_library_path(app: &tauri::AppHandle, path: Option<String>) -> Result<PathBuf, String> {
    match path.filter(|value| !value.trim().is_empty()) {
        Some(value) => Ok(PathBuf::from(value)),
        None => default_library_path(app),
    }
}

fn read_library(path: &Path) -> Result<Option<String>, String> {
    match fs::read_to_string(path) {
        Ok(contents) => Ok(Some(contents)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(format!("Could not read {}: {error}", path.display())),
    }
}

#[tauri::command]
fn load_library_file(app: tauri::AppHandle, path: Option<String>) -> Result<LibraryFile, String> {
    let resolved = resolve_library_path(&app, path)?;
    let contents = read_library(&resolved)?;
    Ok(LibraryFile {
        path: resolved.to_string_lossy().into_owned(),
        contents,
    })
}

#[tauri::command]
fn save_library_file(
    app: tauri::AppHandle,
    path: Option<String>,
    contents: String,
) -> Result<String, String> {
    serde_json::from_str::<serde_json::Value>(&contents)
        .map_err(|error| format!("RiftDrift refused to save invalid library data: {error}"))?;

    let resolved = resolve_library_path(&app, path)?;
    if let Some(parent) = resolved.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("Could not create {}: {error}", parent.display()))?;
    }

    let temporary = resolved.with_extension("riftdrift.tmp");
    fs::write(&temporary, contents)
        .map_err(|error| format!("Could not write {}: {error}", temporary.display()))?;
    fs::rename(&temporary, &resolved)
        .map_err(|error| format!("Could not replace {}: {error}", resolved.display()))?;
    Ok(resolved.to_string_lossy().into_owned())
}

#[cfg(target_os = "macos")]
fn macos_file_dialog(script: &str) -> Result<Option<String>, String> {
    let output = Command::new("osascript")
        .args(["-e", script])
        .output()
        .map_err(|error| format!("Could not open the file picker: {error}"))?;

    if !output.status.success() {
        let message = String::from_utf8_lossy(&output.stderr);
        if message.contains("-128") || message.contains("User canceled") {
            return Ok(None);
        }
        return Err(format!("The file picker failed: {}", message.trim()));
    }

    let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
    Ok((!path.is_empty()).then_some(path))
}

#[tauri::command]
fn pick_library_file() -> Result<Option<String>, String> {
    #[cfg(target_os = "macos")]
    {
        return macos_file_dialog(
            "POSIX path of (choose file with prompt \"Open a RiftDrift library\")",
        );
    }

    #[cfg(not(target_os = "macos"))]
    Err("The native library picker is currently available on macOS only".to_string())
}

#[tauri::command]
fn pick_library_save_path() -> Result<Option<String>, String> {
    #[cfg(target_os = "macos")]
    {
        return macos_file_dialog(
            "POSIX path of (choose file name with prompt \"Save the portable RiftDrift library\" default name \"RiftDrift Library.riftdrift\")",
        );
    }

    #[cfg(not(target_os = "macos"))]
    Err("The native library picker is currently available on macOS only".to_string())
}

#[tauri::command]
fn take_opened_library_path(
    state: tauri::State<'_, PortableLibraryState>,
) -> Result<Option<String>, String> {
    state
        .opened_path
        .lock()
        .map(|mut path| path.take())
        .map_err(|_| "The opened library path is unavailable".to_string())
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct TerminalOutput {
    session_id: u64,
    data: Vec<u8>,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct TerminalExit {
    session_id: u64,
}

#[tauri::command]
fn create_terminal(
    app: tauri::AppHandle,
    state: tauri::State<'_, TerminalState>,
    rows: u16,
    cols: u16,
    cwd: Option<String>,
) -> Result<u64, String> {
    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize {
            rows: rows.max(2),
            cols: cols.max(2),
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|error| format!("Could not open PTY: {error}"))?;

    let shell = env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".to_string());
    let uses_zsh = Path::new(&shell)
        .file_name()
        .is_some_and(|name| name == "zsh");
    let home_directory = env::var("HOME").unwrap_or_else(|_| "/".to_string());
    let working_directory = cwd
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| home_directory.clone());
    let mut command = CommandBuilder::new(shell);
    command.arg("-l");
    command.cwd(working_directory);
    command.env("TERM", "xterm-256color");
    command.env("COLORTERM", "truecolor");
    command.env("CLICOLOR", "1");
    command.env("LSCOLORS", "Gxfxcxdxbxegedabagacad");
    command.env(
        "GREP_COLORS",
        "ms=01;31:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36",
    );
    command.env("TERM_PROGRAM", "RiftDrift");
    command.env("TERM_PROGRAM_VERSION", env!("CARGO_PKG_VERSION"));

    if uses_zsh {
        match prepare_zsh_integration(&app) {
            Ok(integration_directory) => {
                let user_zdotdir = env::var("ZDOTDIR")
                    .ok()
                    .filter(|value| !value.trim().is_empty())
                    .unwrap_or(home_directory);
                command.env("RIFTDRIFT_USER_ZDOTDIR", user_zdotdir);
                command.env(
                    "RIFTDRIFT_ZSH_HIGHLIGHTER",
                    integration_directory.join("riftdrift-highlighting.zsh"),
                );
                command.env("ZDOTDIR", integration_directory);
            }
            Err(error) => log::warn!("RiftDrift command highlighting is unavailable: {error}"),
        }
    }

    let child = pair
        .slave
        .spawn_command(command)
        .map_err(|error| format!("Could not start shell: {error}"))?;
    drop(pair.slave);

    let mut reader = pair
        .master
        .try_clone_reader()
        .map_err(|error| format!("Could not read PTY: {error}"))?;
    let writer = pair
        .master
        .take_writer()
        .map_err(|error| format!("Could not write PTY: {error}"))?;

    let session_id = state.next_id.fetch_add(1, Ordering::Relaxed);
    let scrollback = Arc::new(Mutex::new(Vec::new()));
    let reader_scrollback = Arc::clone(&scrollback);
    let event_app = app.clone();

    thread::spawn(move || {
        let mut buffer = [0_u8; 8192];
        loop {
            match reader.read(&mut buffer) {
                Ok(0) | Err(_) => break,
                Ok(count) => {
                    let chunk = buffer[..count].to_vec();
                    if let Ok(mut saved) = reader_scrollback.lock() {
                        saved.extend_from_slice(&chunk);
                        if saved.len() > MAX_SCROLLBACK_BYTES {
                            let overflow = saved.len() - MAX_SCROLLBACK_BYTES;
                            saved.drain(..overflow);
                        }
                    }
                    let _ = event_app.emit(
                        "terminal-output",
                        TerminalOutput {
                            session_id,
                            data: chunk,
                        },
                    );
                }
            }
        }
        let _ = event_app.emit("terminal-exit", TerminalExit { session_id });
    });

    let session = TerminalSession {
        master: pair.master,
        writer,
        child,
        scrollback,
    };
    state
        .sessions
        .lock()
        .map_err(|_| "Terminal state is unavailable".to_string())?
        .insert(session_id, session);

    Ok(session_id)
}

#[tauri::command]
fn write_terminal(
    state: tauri::State<'_, TerminalState>,
    session_id: u64,
    data: Vec<u8>,
) -> Result<(), String> {
    let mut sessions = state
        .sessions
        .lock()
        .map_err(|_| "Terminal state is unavailable".to_string())?;
    let session = sessions
        .get_mut(&session_id)
        .ok_or_else(|| "Terminal session no longer exists".to_string())?;
    session
        .writer
        .write_all(&data)
        .and_then(|_| session.writer.flush())
        .map_err(|error| format!("Could not write to terminal: {error}"))
}

#[tauri::command]
fn resize_terminal(
    state: tauri::State<'_, TerminalState>,
    session_id: u64,
    rows: u16,
    cols: u16,
) -> Result<(), String> {
    let sessions = state
        .sessions
        .lock()
        .map_err(|_| "Terminal state is unavailable".to_string())?;
    let session = sessions
        .get(&session_id)
        .ok_or_else(|| "Terminal session no longer exists".to_string())?;
    session
        .master
        .resize(PtySize {
            rows: rows.max(2),
            cols: cols.max(2),
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|error| format!("Could not resize terminal: {error}"))
}

#[tauri::command]
fn terminal_scrollback(
    state: tauri::State<'_, TerminalState>,
    session_id: u64,
) -> Result<Vec<u8>, String> {
    let sessions = state
        .sessions
        .lock()
        .map_err(|_| "Terminal state is unavailable".to_string())?;
    let session = sessions
        .get(&session_id)
        .ok_or_else(|| "Terminal session no longer exists".to_string())?;
    session
        .scrollback
        .lock()
        .map(|saved| saved.clone())
        .map_err(|_| "Terminal scrollback is unavailable".to_string())
}

#[tauri::command]
fn close_terminal(state: tauri::State<'_, TerminalState>, session_id: u64) -> Result<(), String> {
    let mut session = state
        .sessions
        .lock()
        .map_err(|_| "Terminal state is unavailable".to_string())?
        .remove(&session_id);
    if let Some(ref mut terminal) = session {
        let _ = terminal.child.kill();
    }
    Ok(())
}

#[tauri::command]
fn detach_terminal(app: tauri::AppHandle, session_id: u64, name: String) -> Result<(), String> {
    let label = format!("terminal-{session_id}");
    if let Some(window) = app.get_webview_window(&label) {
        window.set_focus().map_err(|error| error.to_string())?;
        return Ok(());
    }
    let safe_name = name.replace(' ', "%20");
    let url = format!("index.html?session={session_id}&name={safe_name}");
    let window_builder = WebviewWindowBuilder::new(&app, label, WebviewUrl::App(url.into()))
        .title(format!("RiftDrift — {name}"))
        .inner_size(980.0, 700.0)
        .min_inner_size(720.0, 520.0)
        .decorations(true)
        .center();

    #[cfg(target_os = "macos")]
    let window_builder = window_builder
        .title_bar_style(tauri::TitleBarStyle::Overlay)
        .hidden_title(true);

    window_builder
        .build()
        .map(|_| ())
        .map_err(|error| format!("Could not create window: {error}"))
}

#[tauri::command]
fn window_control(window: WebviewWindow, action: String) -> Result<(), String> {
    match action.as_str() {
        "close" => window.close(),
        "minimize" => window.minimize(),
        "maximize" => {
            if window.is_maximized().map_err(|error| error.to_string())? {
                window.unmaximize()
            } else {
                window.maximize()
            }
        }
        "drag" => window.start_dragging(),
        _ => return Err("Unknown window action".to_string()),
    }
    .map_err(|error| error.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let startup_library = env::args().skip(1).find(|argument| {
        Path::new(argument)
            .extension()
            .is_some_and(|extension| extension.eq_ignore_ascii_case("riftdrift"))
    });
    let library_state = PortableLibraryState {
        opened_path: Mutex::new(startup_library),
    };

    let application = tauri::Builder::default()
        .manage(TerminalState::default())
        .manage(library_state)
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            create_terminal,
            write_terminal,
            resize_terminal,
            terminal_scrollback,
            close_terminal,
            detach_terminal,
            window_control,
            load_library_file,
            save_library_file,
            pick_library_file,
            pick_library_save_path,
            take_opened_library_path,
        ])
        .build(tauri::generate_context!())
        .expect("error while building RiftDrift");

    application.run(|app, event| {
        #[cfg(target_os = "macos")]
        if let tauri::RunEvent::Opened { urls } = event {
            if let Some(path) = urls
                .into_iter()
                .filter_map(|url| url.to_file_path().ok())
                .find(|path| {
                    path.extension()
                        .is_some_and(|extension| extension.eq_ignore_ascii_case("riftdrift"))
                })
            {
                let path = path.to_string_lossy().into_owned();
                if let Ok(mut opened_path) = app.state::<PortableLibraryState>().opened_path.lock()
                {
                    *opened_path = Some(path.clone());
                }
                let _ = app.emit("library-file-opened", path);
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::write_zsh_integration;
    use portable_pty::{native_pty_system, CommandBuilder, PtySize};
    use std::{
        fs,
        io::Read,
        process::Command,
        time::{SystemTime, UNIX_EPOCH},
    };

    #[test]
    fn zsh_integration_loads_user_config_and_keeps_subcommands_bright() {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time should be valid")
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "riftdrift-zsh-test-{}-{unique}",
            std::process::id()
        ));
        let integration = root.join("integration");
        let user_config = root.join("user");
        fs::create_dir_all(&user_config).expect("test user config should be created");
        fs::write(
            user_config.join(".zshrc"),
            "export RIFTDRIFT_TEST_RC=loaded\n",
        )
        .expect("test zshrc should be written");
        write_zsh_integration(&integration).expect("integration files should be written");

        let output = Command::new("/bin/zsh")
            .args([
                "-ilc",
                "print -r -- $RIFTDRIFT_TEST_RC; BUFFER='git status --short && git log'; _riftdrift_highlight_command_line; print -rl -- $region_highlight",
            ])
            .env("ZDOTDIR", &integration)
            .env("RIFTDRIFT_USER_ZDOTDIR", &user_config)
            .env(
                "RIFTDRIFT_ZSH_HIGHLIGHTER",
                integration.join("riftdrift-highlighting.zsh"),
            )
            .output()
            .expect("test zsh should run");
        let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        fs::remove_dir_all(&root).expect("temporary zsh integration should be removed");

        assert!(output.status.success(), "zsh failed: {stderr}");
        assert!(
            stdout.contains("loaded"),
            "user zshrc was not loaded: {stdout}"
        );
        assert!(
            stdout.contains("0 3 fg=cyan memo=riftdrift"),
            "command was not highlighted: {stdout}"
        );
        assert!(
            stdout.contains("4 10 fg=default memo=riftdrift")
                && stdout.contains("26 29 fg=default memo=riftdrift"),
            "subcommands were not kept at the terminal foreground: {stdout}"
        );
    }

    #[test]
    fn shell_runs_inside_a_pty() {
        let pair = native_pty_system()
            .openpty(PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("PTY should open");
        let mut reader = pair
            .master
            .try_clone_reader()
            .expect("PTY should be readable");
        let mut command = CommandBuilder::new("/bin/zsh");
        command.args(["-lc", "printf riftdrift-pty-ok"]);
        let mut child = pair.slave.spawn_command(command).expect("zsh should start");
        drop(pair.slave);
        let output_reader = std::thread::spawn(move || {
            let mut output = Vec::new();
            reader
                .read_to_end(&mut output)
                .expect("PTY output should be readable");
            output
        });
        child.wait().expect("zsh should finish");
        let output = output_reader.join().expect("PTY reader should finish");
        assert!(
            String::from_utf8_lossy(&output).contains("riftdrift-pty-ok"),
            "unexpected PTY output: {:?}",
            String::from_utf8_lossy(&output)
        );
    }
}
